Added product details #30
schonherz-ui-2016/webshop pull request #31
Opened 2016-12-09 18:59 UTC by krisztianm

Fixes #30

2016-12-11 15:51 UTC, zsoltgyongyosi requested changes

2016-12-11 15:51 UTC, zsoltgyongyosi commented on app/src/productDetailsController.js
> +                url: 'http://localhost:1337/product/{id}'
We have to provide an explicit `id` to the backend. Please check out the `$routeParams` service.

2016-12-11 15:51 UTC, zsoltgyongyosi commented on app/templates/productDetails.html
> +<div class="col-md-8" ng-repeat="product in products">
We only have 1 product in this case.

2016-12-11 15:51 UTC, zsoltgyongyosi commented on app/templates/productDetails.html
> +    <img src="http://lorempixel.com/120/40/abstract/" alt="Product Image">
Please ensure that this image fills the column via CSS.

2016-12-14 09:23 UTC, zsoltgyongyosi requested changes

2016-12-14 09:23 UTC, zsoltgyongyosi commented on scss/index.scss
> +    background: url("http://lorempixel.com/120/40/abstract/") center;
This one will have to be an `<img/>` tag, because it's not a static image.

2016-12-14 09:23 UTC, zsoltgyongyosi commented on scss/index.scss
> +.productDetails {
Please use kebab-case for classes.

2016-12-14 09:23 UTC, zsoltgyongyosi commented on app/src/routing.js
> +                    templateUrl: 'templates/productDetails.html',
Please remove the duplicate key.

2016-12-14 14:30 UTC, krisztianm commented on app/src/routing.js
> +                    templateUrl: 'templates/productDetails.html',
@zsoltgyongyosi Could you please give more details about this request?

2016-12-14 15:10 UTC, zsoltgyongyosi commented on app/src/routing.js
> +                    templateUrl: 'templates/productDetails.html',
`templateUrl` is duplicated

2016-12-14 23:43 UTC, zsoltgyongyosi approved these changes

2016-12-14 23:43 UTC, merged